---
- name: Wait for SSH to come up
  wait_for:
    host: "{{ item.public_dns_name }}"
    port: 22
    delay: 0
    timeout: 320
    state: started
  with_items: "{{ ec2.tagged_instances }}"

- name: Wait for SSH to come up
  wait_for:
    host: "{{ item.public_dns_name }}"
    port: 22
    delay: 0
    timeout: 320
    state: started
  with_items: "{{ ec2.tagged_instances }}"

